### PR TITLE
Using new apache beam version

### PR DESCRIPTION
**Pull request by Komei22**
This pull request recreate by following discussion.
https://github.com/yu-iskw/kuromoji-for-bigquery/pull/1#issuecomment-658542841

This pull request updated apache beam and its dependent packages version. This is because the current apache beam version used in kuromoji-for-bigquery is deprecated.

ref: https://cloud.google.com/dataflow/docs/support/sdk-version-support-status?hl=ja#apache-beam-sdks-2x

### CODE REVIEW

**Comment by yu-iskw** [comment]
@Komei22 Thank you for creating the PR! I look into the error of the CI.

**Comment by yu-iskw** [comment]
I will stop tests with `openjdk7 at  https://github.com/yu-iskw/kuromoji-for-bigquery/pull/6 . The CI at the PR should be going to pass after merging it.

**Comment by yu-iskw** [comment]
@Komei22 Can you rebase your branch with the master branch?  I have removed the test environment with `openjdk7`.

**Comment by Komei22** [comment]
@yu-iskw Thank you for your response. I merged your master branch. Then, the CI passed.

**Review by yu-iskw — APPROVED** [review]
LGTM

**Comment by yu-iskw** [comment]
@Komei22 Merged. Thank you for the contribution. That would be super helpful to me, since I haven't maintained the repository for a while.

**Pull request merged**
